### ISSUE TITLE
Missing keyboard when searching and Saved to Home Screen on iPhone

### ISSUE THREAD

**Issue by matt-2s** [navarog/expeditions#1]
On iPhone 14 Pro Max, iOS Version 17.3.1.

In Safari I add the Expeditions Card Search to my Home Screen.
When I launch it I see the Expeditions Card Search as a web app.
If I tap in the search text area the keyboard does not appear, but does show the bar that appears above the keyboard.
This does not happen if I am in Safari.

![image](https://github.com/navarog/expeditions/assets/72248780/0e670d2f-b21f-438c-9684-4bf27e572ac0)

**Comment by matt-2s** [comment]
Updated to iOS 10.4 and the keyboard now shows.

**Comment by navarog** [comment]
Thanks for letting us know about this bug, it would be super difficult for me to debug it without an iPhone.
