### ISSUE TITLE
wingsearch question

### ISSUE THREAD

**Issue by gitHu6-newb** [navarog/expeditions#3]
Sorry for contacting you in this convoluted manner, but you helped with Robbie's fan art, correct? I noticed the Asia birds don't have silhouettes so I started making them. Can you take a look at 
https://raw.githubusercontent.com/gitHu6-newb/imenages/main/silhouettes/361.png
And if you have any tips on what I can do better (size adjustments, placement, anything) I would appreciate it!

Thanks

**Comment by navarog** [comment]
No problem, thanks for reaching out!
